[package]
name = "MOCPy"
version = "0.12.0"
authors = [
  "Matthieu Baumann <matthieu.baumann@astro.unistra.fr>", 
  "Thomas Boch <thomas.boch@astro.unistra.fr>",
  "Manon Marchand <manon.marchand@astro.unisrta.fr>",
  "F.-X. Pineau <francois-xavier.pineau@astro.unistra.fr>",
]
edition = "2018"
license = "BSD-3-Clause"
readme = "README.rst"
categories = ["algorithms", "science"]
repository = "https://github.com/cds-astro/mocpy"
description = "MOC parsing and manipulation in Python"
documentation = "https://cds-astro.github.io/mocpy"

[badges]
maintenance = { status = "actively-developed" }

[lib]
name = "mocpy"
path = "src/lib.rs"
test = true
doctest = true
bench = true
crate-type = ["cdylib"]

[dependencies]
# moc = "0.9"
moc = { git = 'https://github.com/cds-astro/cds-moc-rust', branch = 'main', features = ["storage"] }
healpix = { package = "cdshealpix", version = "0.6" }
# healpix = { package = "cdshealpix", git = 'https://github.com/cds-astro/cds-healpix-rust', branch = 'master' }
num = "0.4"
time = "*"
rayon = "1.6"

[dependencies.numpy]
version = "0.18"

[dependencies.ndarray]
version = "0.15"
default-features = false # do not include the default features, and optionally
                         # cherry-pick individual features
features = ["rayon"]

[dependencies.pyo3]
version = "0.18"
features = ["extension-module"]

[dev-dependencies]
rand = "0.8"

[profile.release]
opt-level = 3

[profile.dev]
opt-level = 0



